project_root: "/root/autodl-tmp/SSR-VQA"

sku_root: "/root/autodl-tmp/datasets/SKU110K_fixed/SKU110K_fixed"
sku_images: "/root/autodl-tmp/datasets/SKU110K_fixed/SKU110K_fixed/images"
sku_annotations: "/root/autodl-tmp/datasets/SKU110K_fixed/SKU110K_fixed/annotations"

gap_zip: "/root/autodl-tmp/datasets/gapDetectionDatasets-main.zip"
gap_root: "/root/autodl-tmp/datasets/gapDetectionDatasets-main/gapDetectionDatasets-main"

processed_root: "/root/autodl-tmp/SSR-VQA/data/processed"
output_root: "/root/autodl-tmp/SSR-VQA/outputs"